# Notebook de test


## Importation des bibliothèques


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy

import spacy
import random
import math
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.ensemble import RandomForestRegressor

## Fonctions utiles

In [2]:
def progress_bar(iteration, total, prefix='', suffix='', decimals=1, length=50, fill='█'):
    """Fonction d'affichage de progress bar, récupérée sur le Notebook du TD1 de Data Sciences de Myriam Tami
    """
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
    filled_length = int(length * iteration // total)
    bar = fill * filled_length + '-' * (length - filled_length)
    print(f'\r{prefix} |{bar}| {percent}% {suffix}', end='\r')
    # Print New Line on Complete
    if iteration == total:
        print()
                
def raw_to_tokens(raw_string, spacy_nlp):
        # Write code for lower-casing
    string = raw_string.lower()

    # Write code to normalize the accents
    string = normalize_accent(string)

    # Write code to tokenize
    spacy_tokens = spacy_nlp(string)
    

    # Write code to remove punctuation tokens and create string tokens
    string_tokens = [token.orth_ for token in spacy_tokens if not token.is_punct if not token.is_stop]
    # Write code to join the tokens back into a single string
    clean_string = " ".join(string_tokens)

    return clean_string


def normalize_accent(string):
    string = string.replace('á', 'a')
    string = string.replace('â', 'a')
    string = string.replace('à', 'a')
    
    string = string.replace('é', 'e')
    string = string.replace('è', 'e')
    string = string.replace('ê', 'e')
    string = string.replace('ë', 'e')

    string = string.replace('î', 'i')
    string = string.replace('ï', 'i')
    string = string.replace('n°','n')
    string = string.replace('ö', 'o')
    string = string.replace('ô', 'o')
    string = string.replace('ò', 'o')
    string = string.replace('ó', 'o')

    string = string.replace('ù', 'u')
    string = string.replace('û', 'u')
    string = string.replace('ü', 'u')

    string = string.replace('ç', 'c')

    return string

## Récupération des données

récupération du dico français

In [3]:
spacy_nlp = spacy.load("fr_core_news_sm")

récupération des vecteurs x_data et y_data

In [7]:
Reload = False
filename = "X_dt.mat"

Y_train_filename = ".\data\Y_train_CVw08PX.csv"
#pour y_data (le product type id)
y_data = pd.read_csv(Y_train_filename,sep=',')['prdtypecode'] #récupération de la bonne colonne prdtypecode

if not Reload:
    X_data = scipy.io.loadmat('.\data\\' + filename)['data']
else:
    Xtrain_filename = ".\data\X_train_update.csv"   
    #pour le x_data (ici la designation, ie string)
    X_data = []
    raw_data = pd.read_csv(Xtrain_filename,sep=',')
    design = raw_data['designation']
    for k in range(len(design)):
        X_data.append(raw_to_tokens(design[k],spacy_nlp))
        progress_bar(k + 1,len(design), prefix='Preprocessing train:', suffix='Complété', length=50)
            


Enregistrement de X_data en mémoire pour éviter de le reload à chaque fois

In [8]:
mdic = {"data": X_data}


scipy.io.savemat('.\data\\' + filename,mdic)

In [5]:

def import_data(spacy_nlp,reload):
    
    
    
    y = y_data
    filename = "X_dt.mat"
    part =20
    
    
    if reload:
        

       
        raw_data = raw_data.drop(labels='imageid',axis=1)

        descrip = raw_data['description']
        
        
        X_data = []
        
            header.
            progress_bar(k + 1,len(design)//part, prefix='Preprocessing train:', suffix='Complété', length=50)
        mdic = {"data": X_data}
        scipy.io.savemat('.\data\\' + filename,mdic)
    else:
        X_data = scipy.io.loadmat('.\data\\' + filename)['data']
    
    tfidf = TfidfVectorizer()
    X_tfidf_sample = tfidf.fit_transform(X_data)
    print(X_tfidf_sample.shape)
    return train_test_split(X_tfidf_sample[:len(X_data)//part],y[:len(X_data)//part],test_size=0.25,random_state=42,shuffle=True)

IndentationError: unexpected indent (264228122.py, line 21)

In [ ]:
spacy_nlp = spacy.load("fr_core_news_sm")

In [ ]:
hist_tab_y =pd.DataFrame(y_train.prdtypecode.value_counts()).reset_index()
hist_tab_y.columns = ['Code_produit', 'Count']
hist_y = hist_tab_y.sort_values("Count", ascending = True)
plt.figure(figsize = (10,10))
sns.barplot(hist_y.Count,hist_y.Code_produit , orient = "h", order = hist_y.Code_produit.tolist() )
plt.title("Barplot des différents code produit");

In [ ]:


# Load spaCy for french


Preprocessing train: |██████████████████████████████████████████████████| 100.0% Complété


In [ ]:
tfidf = TfidfVectorizer()

# Write code to vectorize the sample text
X_tfidf_sample = tfidf.fit_transform(X_data)

print("Shape of the TF-IDF Matrix:")
print(X_tfidf_sample.shape)
print("TF-IDF Matrix:")
print(X_tfidf_sample.todense())
print(tfidf.get_feature_names_out())



Shape of the TF-IDF Matrix:
(16983, 29981)
TF-IDF Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['00' '000' '0000' ... 'ø75' 'ø80' 'úlaire']


In [ ]:
Dd = X_tfidf_sample.todense()
print(Dd.shape)
sum = 0
for k in range(len(Dd)):
    for i in range(len(Dd[0])):
        # print(Dd[k,i])
        sum+= Dd[k,i]
        
print(sum)

(16983, 29981)
2.9006834528632526


In [ ]:
params = {
    'Random forest': {'n_estimators': [200, 400, 600, 800]}
}

models = {
    'Random forest': RandomForestRegressor(
        n_jobs=-1
    )}


n_folds = 10

cv = KFold(n_splits=n_folds, shuffle=True)
X = X_tfidf_sample


for name,model in models.items():
    grid_search = GridSearchCV(
        estimator=model,
        param_grid=params[name],
        scoring='neg_mean_squared_error',
        return_train_score=True,
        cv=cv,
    ).fit(X, y)