# fonctions normalisation du texte

In [8]:
import numpy as np
import pandas as pd


import random
import math
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV, KFold

from sklearn.ensemble import RandomForestRegressor

In [4]:


# Load spaCy for french


Preprocessing train: |██████████████████████████████████████████████████| 100.0% Complété


In [9]:
tfidf = TfidfVectorizer()

# Write code to vectorize the sample text
X_tfidf_sample = tfidf.fit_transform(X_data)

print("Shape of the TF-IDF Matrix:")
print(X_tfidf_sample.shape)
print("TF-IDF Matrix:")
print(X_tfidf_sample.todense())
print(tfidf.get_feature_names_out())



Shape of the TF-IDF Matrix:
(16983, 29981)
TF-IDF Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['00' '000' '0000' ... 'ø75' 'ø80' 'úlaire']


In [10]:
Dd = X_tfidf_sample.todense()
print(Dd.shape)
sum = 0
for k in range(len(Dd)):
    for i in range(len(Dd[0])):
        # print(Dd[k,i])
        sum+= Dd[k,i]
        
print(sum)

(16983, 29981)
2.9006834528632526


In [ ]:
params = {
    'Random forest': {'n_estimators': [200, 400, 600, 800]}
}

models = {
    'Random forest': RandomForestRegressor(
        n_jobs=-1
    )}


n_folds = 10

cv = KFold(n_splits=n_folds, shuffle=True)
X = X_tfidf_sample


for name,model in models.items():
    grid_search = GridSearchCV(
        estimator=model,
        param_grid=params[name],
        scoring='neg_mean_squared_error',
        return_train_score=True,
        cv=cv,
    ).fit(X, y)