# fonctions normalisation du texte

In [8]:
import numpy as np
import pandas as pd


import random
import math
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:

        
def progress_bar(iteration, total, prefix='', suffix='', decimals=1, length=50, fill='█'):
    """Fonction d'affichage de progress bar, récupérée sur le Notebook du TD1 de Data Sciences de Myriam Tami
    """
    percent = ("{0:." + str(decimals) + "f}").format(100 * (iteration / float(total)))
    filled_length = int(length * iteration // total)
    bar = fill * filled_length + '-' * (length - filled_length)
    print(f'\r{prefix} |{bar}| {percent}% {suffix}', end='\r')
    # Print New Line on Complete
    if iteration == total:
        print()

def normalize_accent(string):
    string = string.replace('á', 'a')
    string = string.replace('â', 'a')

    string = string.replace('é', 'e')
    string = string.replace('è', 'e')
    string = string.replace('ê', 'e')
    string = string.replace('ë', 'e')

    string = string.replace('î', 'i')
    string = string.replace('ï', 'i')

    string = string.replace('ö', 'o')
    string = string.replace('ô', 'o')
    string = string.replace('ò', 'o')
    string = string.replace('ó', 'o')

    string = string.replace('ù', 'u')
    string = string.replace('û', 'u')
    string = string.replace('ü', 'u')

    string = string.replace('ç', 'c')

    return string

In [3]:
def raw_to_tokens(raw_string, spacy_nlp):
    # Write code for lower-casing
    string = raw_string.lower()

    # Write code to normalize the accents
    string = normalize_accent(string)

    # Write code to tokenize
    spacy_tokens = spacy_nlp(string)
    

    # Write code to remove punctuation tokens and create string tokens
    string_tokens = [token.orth_ for token in spacy_tokens if not token.is_punct]
    # Write code to join the tokens back into a single string
    clean_string = " ".join(string_tokens)

    return clean_string

In [4]:
import spacy

# Load spaCy for french
spacy_nlp = spacy.load("fr_core_news_sm")

In [6]:
Xtrain_filename = ".\data\X_train_update.csv"

raw_data = pd.read_csv(Xtrain_filename,sep=','
                   )
# print(raw_data.info())
#on dégage l'image id
raw_data = raw_data.drop(labels='imageid',axis=1)
# print(raw_data.info())

descrip = raw_data['description']
design = raw_data['designation']


part = 5
X_data = []
for k in range(len(design)//part):
    X_data.append(raw_to_tokens(design[k],spacy_nlp))
    progress_bar(k + 1,len(design)//part, prefix='Preprocessing train:', suffix='Complété', length=50)






Preprocessing train: |██████████████████████████████████████████████████| 100.0% Complété


In [9]:
tfidf = TfidfVectorizer()

# Write code to vectorize the sample text
X_tfidf_sample = tfidf.fit_transform(X_data)

print("Shape of the TF-IDF Matrix:")
print(X_tfidf_sample.shape)
print("TF-IDF Matrix:")
print(X_tfidf_sample.todense())
print(tfidf.get_feature_names_out())



Shape of the TF-IDF Matrix:
(16983, 29981)
TF-IDF Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['00' '000' '0000' ... 'ø75' 'ø80' 'úlaire']


In [19]:
Dd = X_tfidf_sample.todense()
print(Dd.shape)
sum = 0
for k in range(len(Dd)):
    for i in range(len(Dd[0])):
        # print(Dd[k,i])
        sum+= Dd[k,i]
        
print(sum)

(16983, 29981)
2.9006834528632526
